skip-check:
  - CKV_AWS_28
  - CKV_AWS_119
  - CKV_AWS_300 # Ensure S3 lifecycle configuration sets period for aborting failed uploads, Guide: https://docs.prismacloud.io/en/enterprise-edition/policy-reference/aws-policies/aws-general-policies/bc-aws-30
